# -*- coding: utf-8 -*-
"""Crimes in India.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10r2dBQ88-9_MvpNVr0P9QA8FYdJN-WvZ
"""

!pip install --upgrade plotly
!pip install --upgrade geopandas

import pandas as pd
import numpy as np
import geopandas as gpd
import folium
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
import plotly.figure_factory as ff
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

df=pd.read_csv('/content/drive/MyDrive/crime/01_District_wise_crimes_committed_IPC_2001_2012.csv')

"""# EDA"""

df.head()

df.shape

df.columns

df.info()

df.describe()

df.dtypes

df.isnull().values.any()

df=df[df['DISTRICT']=='TOTAL']

df.drop(['DISTRICT'],axis=1,inplace=True)

df=df.set_index(['STATE/UT'])

df=df.reset_index()

df

df['STATE/UT'].unique()

len(df['STATE/UT'].unique())

df=df.groupby(['STATE/UT','YEAR']).sum().reset_index()
df

"""# India Crime Visuals

## Sunburst graph
"""

fig2=px.sunburst(df,path=['STATE/UT','YEAR'],values='TOTAL IPC CRIMES',title="State and year wise segregation")
fig2.show()

"""## Tree map"""

df.groupby(['YEAR']).sum().reset_index()

fig3=px.treemap(df,path=['STATE/UT','YEAR'],values='TOTAL IPC CRIMES')
fig3.show()

"""## Year wise total crime stats"""

plt.figure(figsize=(8,12))
plt.bar(df['YEAR'], df['TOTAL IPC CRIMES'])
plt.xlabel('Year')
plt.ylabel('Total IPC Crimes')
plt.title('Year wise total crimes')

columns = ['MURDER','RAPE','KIDNAPPING & ABDUCTION','DACOITY','ROBBERY','BURGLARY','AUTO THEFT','RIOTS','CHEATING','COUNTERFIETING', 'ARSON', 'HURT/GREVIOUS HURT',
       'DOWRY DEATHS', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY']
len(columns)

import itertools
sns.set_context("talk")
plt.style.use("fivethirtyeight")
palette = itertools.cycle(sns.color_palette("dark"))
plt.figure(figsize=(20,30))
plt.style.use('fivethirtyeight')
for i,column in enumerate(columns):
    plt.subplot(7,2,i+1)
    ax= sns.barplot(data= df,x='YEAR',y= column ,color=next(palette) )
    plt.xlabel('')
    plt.ylabel('')
    plt.title(column,size = 20)
    for p in ax.patches:
             ax.annotate("%.f" % p.get_height(), (p.get_x() + p.get_width() / 2., p.get_height()),
                 ha='center', va='center', fontsize=15, color='black', xytext=(0, 8),
                 textcoords='offset points')
    
plt.tight_layout()
plt.subplots_adjust(hspace= .3)
plt.show()

"""## State wise total crime """

ind=gpd.read_file('/content/drive/MyDrive/crime/india_state_geo.json~1/india_state_geo.json')

ind.shape

ind.columns

ind.dtypes

ind.isnull().values.any()

ind.drop(['ID_0','ISO','NL_NAME_1','VARNAME_1','ENGTYPE_1','ID_1'],axis=1,inplace=True)

ind.rename(columns={'NAME_0':'country','NAME_1':'state','TYPE_1':'type'},inplace=True)

ind.head()

ind['state'].unique()

len(ind['state'].unique())

fig1=df.groupby(['STATE/UT']).sum().reset_index()
fig1.drop('YEAR',axis=1,inplace=True)

fig1.head(10)

ind.drop(9,inplace=True)

ind.set_index('state',inplace=True)
ind.reset_index(inplace=True)

merged=ind.merge(fig1, how='inner',left_on=ind.index,right_on=fig1.index)
merged.drop(['key_0','STATE/UT'],axis=1,inplace=True)

merged.head()

fig, ax = plt.subplots(1, figsize=(15, 15))
ax.set_title('State-wise IPC crimes (2001-2012)',fontdict={'fontsize': '15', 'fontweight' : '3'})
fig = merged.plot(column='TOTAL IPC CRIMES', cmap='Reds', linewidth=0.5, ax=ax, edgecolor='0.2',legend=True)

fig1.set_index('STATE/UT',inplace=True)
fig1['TOTAL IPC CRIMES'].plot(kind='barh',figsize=(10,30))

states=ind['state'].unique()

"""## Types of Crimes"""

df.columns

murder=df['MURDER'].sum()
rape=df['RAPE'].sum()
kidnapping=df['KIDNAPPING & ABDUCTION'].sum()
robbery=df['ROBBERY'].sum() 
riots=df['RIOTS'].sum() 
dacoity=df['DACOITY'].sum() 
burglary=df['BURGLARY'].sum() 
theft=df['THEFT'].sum() 
cheating=df['CHEATING'].sum() 
counterfieting=df['COUNTERFIETING'].sum() 
dowry=df['DOWRY DEATHS'].sum() 
others=df['TOTAL IPC CRIMES'].sum() - (murder+rape+kidnapping+robbery+riots+dacoity+burglary+theft+cheating+counterfieting+dowry)

crime_type = ['Murder','Rape','Kidnapping','Robbery','Riots','Dacoity','Burglary','Theft','Cheating','Counterfieting','Dowry','Others']
crime_type_vals = [murder,rape,kidnapping,robbery,riots,dacoity,burglary,theft,cheating,counterfieting,dowry,others]

fig3 = go.Figure(data=[go.Pie(labels=crime_type, values=crime_type_vals,sort=False,marker=dict(colors=px.colors.qualitative.G10),textfont_size=12)])
fig3.update_layout(title='Major types of crime in India (2001 - 2012)')
fig3.show()

scy = df.groupby(['YEAR'])['MURDER', 'RAPE', 'KIDNAPPING & ABDUCTION',
        'DACOITY', 'ROBBERY', 'BURGLARY', 'THEFT',
       'AUTO THEFT', 'RIOTS', 'CHEATING', 'COUNTERFIETING', 'ARSON', 'HURT/GREVIOUS HURT',
       'DOWRY DEATHS', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',
       'INSULT TO MODESTY OF WOMEN', 'CRUELTY BY HUSBAND OR HIS RELATIVES',
       'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES',
       'CAUSING DEATH BY NEGLIGENCE'].sum().reset_index()

crimes = ['Murder', 'Rape',
       'Kidnapping and Abduction', 'Dacoity', 'Robbery','Burglary','Theft','Auto theft','Riots','Cheating','Counterfieting','Arson', 'Hurt',
       'Dowry','Assault on women','Insult to modesty of women','Cruelty by husband or relatives','Importation of girls from Foreign countries',
       'Causing death by negliegence']

fig = go.Figure()
fig.add_trace(go.Scatter(x= scy['YEAR'], y= scy['MURDER'],
                    name='Murder',line=dict(color='pink', width=4)))
fig.add_trace(go.Scatter(x= scy['YEAR'], y= scy['RAPE'],
                    name='Rape',line=dict(color='green', width=4)))
fig.add_trace(go.Scatter(x= scy['YEAR'], y= scy['KIDNAPPING & ABDUCTION'],
                    name='Kidnapping and Abduction',line=dict(color='orange', width=4)))
fig.add_trace(go.Scatter(x= scy['YEAR'], y= scy['DACOITY'],
                    name='Dacoity',line=dict(color='yellow', width=4)))
fig.add_trace(go.Scatter(x= scy['YEAR'], y= scy['ROBBERY'],
                    name='Robbery',line=dict(color='black', width=4)))
fig.add_trace(go.Scatter(x= scy['YEAR'], y= scy['ARSON'],
                    name='Arson',line=dict(color='skyblue', width=4)))
fig.add_trace(go.Scatter(x= scy['YEAR'], y= scy['HURT/GREVIOUS HURT'],
                    name='Hurt',line=dict(color='royalblue', width=4)))
fig.add_trace(go.Scatter(x= scy['YEAR'], y= scy['ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY'],
                    name='Assualt on women',line=dict(color='firebrick', width=4)))
fig.add_trace(go.Scatter(x= scy['YEAR'], y= scy['ROBBERY'],
                    mode='lines+markers',
                    name='Robbery'))
fig.add_trace(go.Scatter(x= scy['YEAR'], y= scy['CHEATING'],
                    name='Cheating',line=dict(color='red', width=4)))

fig.update_layout(uniformtext_minsize= 20,
    title_text="Types Crimes(2001-2012)",
    
                 )
    
fig.show()

"""# Rape"""

